spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://127.0.0.1/springcloud_sell?characterEncoding=utf-8&useSSL=false
    username: root
  jpa:
    show-sql: true
  rabbitmq:
    host: localhost
    password: guest
    port: 5672
    username: guest
  redis:
    host: localhost
    port: 6379
zuul:
  # 全部服务忽略敏感头
  sensitive-headers:
  # 自定义路由规则
  routes:
    myProdcut:
      path: /myProdcut/**
      serviceId: product
      # 不过滤 cookie 及一些敏感头
      sensitiveHeaders:
    mysss:
      path: /mysss/**
      serviceId: product
      # 不过滤 cookie 及一些敏感头
      sensitiveHeaders:
    my:
      path: /my/**
      serviceId: product
      # 不过滤 cookie 及一些敏感头
      sensitiveHeaders:
    my1:
      path: /my1/**
      serviceId: product
      # 不过滤 cookie 及一些敏感头
      sensitiveHeaders:
    # 简写
#    product: /myProdcut/**
  # 禁止访问的列表
  ignored-patterns:
    - /**/product/listForOrder
